### ISSUE TITLE
3D model for OLED adapter

### ISSUE THREAD

**Issue by augisbud** [fogbox/m365_display#3]
Hey, do you have 3d models for the oled and arduino pro mini?

**Comment by vaGpl** [comment]
Everything on internet:
https://grabcad.com/library/arduino-pro-mini-1
https://grabcad.com/library/oled-0-96-inch-128x64-screen-chineese-1/details?folder_id=1710465

**Comment by augisbud** [comment]
🤦‍♂️ I mean for the mounting for the scooter
